version: 0.1

phases:
  install:
    commands:
#      - npm install -g nvm
#      - nvm install v6.10.3
      - npm install
      - npm install -g serverless@1.24.1
  build:
    commands:
      - serverless package --package my-artifacts --stage dev --region eu-central-1 -v
  post_build:
    commands:
      - serverless deploy --package my-artifacts --stage dev --region eu-central-1 -v
#  post_build:
#    commands:
#      - serverless -v -s $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2 | cut -d'_' -f3) deploy
#artifacts:
#  files:
#    - my-artifacts*/**
#  discard-paths: yes