version: 0.2

env:
  variables:
    STAGE: 'dev'

phases:
  install:
    commands:
      - echo Entered the install phase...
      - printenv
      - npm install
      - npm install -g serverless@1.24.1
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm run unit
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - SLS_DEBUG=* serverless deploy --stage dev --region eu-central-1 --verbose
      - echo Generate api documantation
      - npm run apidoc
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Deploy Documantation
      - aws s3 sync apidoc/build/ s3://sls-bucket-apidoc-$STAGE
      - echo Build completed on `date`