version: 0.1

phases:
  install:
    commands:
#      - npm install -g nvm
#      - nvm install v6.10.3
      - printenv
      - npm install
  build:
    commands:
      - npm install -g serverless@1.24.1
      - SLS_DEBUG=* serverless -v -s $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2 | cut -d'_' -f3) deploy --stage dev --region eu-central-1 --verbose