resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
          - AttributeName: "arn"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 2
        GlobalSecondaryIndexes:
          - IndexName: AccountIdIndex
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 2
          - IndexName: FunctionArnIndex
            KeySchema:
              - AttributeName: arn
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 2

        TableName: ${self:provider.environment.FUNCTIONS_TABLE}

    InvocationsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
          - AttributeName: "_function"
            AttributeType: "S"
          - AttributeName: "startTime"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: AccountIdIndex
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
              - AttributeName: startTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: FunctionIdIndex
            KeySchema:
              - AttributeName: _function
                KeyType: HASH
              - AttributeName: startTime
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

        TableName: ${self:provider.environment.INVOCATIONS_TABLE}
    AccountsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.ACCOUNTS_TABLE}
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "password"
            AttributeType: "S"
          - AttributeName: "isActive"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: EmailPasswordIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
              - AttributeName: password
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: isActive
            KeySchema:
              - AttributeName: _id
                KeyType: HASH
              - AttributeName: isActive
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: emailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
              - AttributeName: isActive
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USERS_TABLE}
    UsersAccountsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: "_user"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_user"
            KeyType: "HASH"
          - AttributeName: "_account"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: AccountUsers
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
              - AttributeName: _user
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_ACCOUNTS_TABLE}
#    S3BucketStuffBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: sls-bucket-apidoc-${opt:stage}
#        AccessControl: 'PublicRead'
#        WebsiteConfiguration:
#          IndexDocument: index.html
#          ErrorDocument: index.html
#        CorsConfiguration:
#          CorsRules:
#            - AllowedMethods:
#              - GET
#              - HEAD
#              AllowedOrigins:
#              - "*"
#              AllowedHeaders:
#              - "*"
