resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
          - AttributeName: "arn"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: AccountIdIndex
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: FunctionArnIndex
            KeySchema:
              - AttributeName: arn
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        TableName: ${self:provider.environment.FUNCTIONS_TABLE}

    InvocationsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
          - AttributeName: "_function"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: AccountIdIndex
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: FunctionIdIndex
            KeySchema:
              - AttributeName: _function
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        TableName: ${self:provider.environment.INVOCATIONS_TABLE}
    AccountsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.ACCOUNTS_TABLE}
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
#          - AttributeName: "firstName"
#            AttributeType: "S"
#          - AttributeName: "lastName"
#            AttributeType: "S"
          - AttributeName: "email"
            AttributeType: "S"
          - AttributeName: "password"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: EmailPasswordIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
              - AttributeName: password
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USERS_TABLE}
    UsersAccountsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: "_user"
            AttributeType: "S"
          - AttributeName: "_account"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_user"
            KeyType: "HASH"
          - AttributeName: "_account"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: AccountUsers
            KeySchema:
              - AttributeName: _account
                KeyType: HASH
              - AttributeName: _user
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_ACCOUNTS_TABLE}
