functions:
  getFunction:
    handler: src/api/functions/functions.get
    package:
      include:
        - src/api/functions/**
        - src/api/passport/**
    events:
      - http:
          path: /accounts/{id}/functions/{functionId}
          method: get
          cors: true
  listFunctions:
    handler: src/api/functions/functions.list
    package:
      include:
        - src/api/functions/**
        - src/api/passport/**
    events:
      - http:
          path: /accounts/{id}/functions
          method: get
          cors: true
